examples/login/app.js, examples/login/package.json
I have updated the login example to use the newest Express framework and all the separated out middlewares. Also, `package.json` now has version numbers to better deal with newer versions of modules.
=> Updated to use Express ^4.11

package.json
Snyk reports potential issues with some dependencies (`ejs` and `xml-encryption`). Bumped minor version.
=> Updated dependencies to fix Snyk report

lib/passport-wsfed-saml2/saml.js
If the Conditions elements is missing, the expiration validation should return `true`.
The `Conditions` element and the `NotBefore`/`NotOnOrAfter` attributes are optional, see line 822 of https://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf.
=> Pass expiration validation if no restrictions are present

lib/passport-wsfed-saml2/samlp.js, test/samlp.tests.js
Prevents an exception from occurring when `opts.identityProviderUrl` is `null` or `undefined` during a call to `getSamlRequestUrl`.
=> Converts exception to error when calling getSamlRequestUrl with an empty identityProviderUrl

package-lock.json, package.json
Rev'd the version to 3.0.6 for a minor patch that prevents an exception in the case of a missing `identityProviderUrl`
=> Revving the version to 3.0.6 for a patch release

package.json
Bumping the version number for a patch release.
Release will contain the following updates:
* Added tests for the encoded XML value in an AttributeValue field (#74)
^ This includes an update to the xmldom dependency to fix the issue w/ pairs of encoded character entities getting dropped during XML parsing.
* Improve error message when signing certificate is invalid (#72)
=> Creating new patch release 3.0.8

lib/passport-wsfed-saml2/samlp.js, package.json, test/samlp.tests.js
We used to parse `options.identityProviderUrl` assuming it was a string, which failed when it wasn't.
We'd fixed this in Samlp.getSamlRequestUrl(), but its siblings getSamlRequestParams() and getSamlRequestForm() were still susceptible.
=> Fix remaining cases where an invalid identityProviderUrl isn't handled properly

lib/passport-wsfed-saml2/samlp.js, package.json, test/samlp.tests.js
Also moved a couple of tests into the right `describe()`.
=> 3.0.11 Handle exception when signing a malformed requestTemplate

lib/passport-wsfed-saml2/samlp.js, package.json, test/samlp.tests.js
There is a situation in which the @@ VAR @@ can get goofed up and
contain strings that will include part of the template itself. This will
not parse correctly and throws an exception in the replace phase of the
regex matching. I've wrapped it in a try/catch to prevent it from
bringing the process down.
Noting that this area looks problematic as it was recently patched in https://github.com/auth0/passport-wsfed-saml2/pull/88
Version bumped to `3.0.12`.
[Sentry Issue](https://sentry.io/auth0/auth0-server/issues/617753396/events/25564560312/)
✅ This change has unit test coverage
=> DF-38 Wrapping template parse to prevent uncaught

lib/passport-wsfed-saml2/saml.js, test/saml20.tests.js
Changing default clock skew to 3 minutes to adhere to standard industry practice.
Also make clock skew a configurable option.
=> Tighten clock skew checks for SAML.

lib/passport-wsfed-saml2/utils.js
passport-wsfed-saml2 uses a non cryptographically secure RNG based on Math.random to generate request ID.
This PR fixes this issue. The returned id has the same properties: 20 digits long with hex alphabet.
=> Use crypto randombytes for uniqueness

lib/passport-wsfed-saml2/saml.js, test/saml11.tests.js, test/saml20.tests.js
fixes https://github.com/auth0/passport-wsfed-saml2/issues/75
@machuga 
Bugfix for issue `Invalid cert tests break with Node >= 8.7.0 #75`
=> Add support of new error message format  (for OpenSSL errors) of Node.js

lib/passport-wsfed-saml2/saml.js
If the certificate is invalid, x509 throws an exception which is not being handled properly
=> Catch x509 exeptions on invalid certificates

.gitignore, .npmrc, .travis.yml, package.json, test/saml11.tests.js, test/saml20.tests.js
Update x509 to support Node 10 and use the original repo - not the fork since it's published correctly as of 0.3.4 and the memory leak was fixed as of 0.3.2.
=> [Node 10] Update x509

lib/passport-wsfed-saml2/saml.js, package.json
By submitting a PR to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md). Please see the [contributing guidelines](https://github.com/auth0/.github/blob/master/CONTRIBUTING.md) for how to create and submit a high-quality PR for this repo.
Replace `x509` dependency for `node-forge`.
`x509` is abandoned.
=> Change x509 dependency

.github/ci.yml, .gitignore, .travis.yml, README.md, package.json
Travis CI was being super slow. This moves CI to Github actions along with the following changes:
- Run tests in Node 10, 12, 14, 15. (The currently supported versions only. https://nodejs.org/en/about/releases/ )
- Add coverage report
N/A
=> [build] Move CI away from Travis and to Github Actions

lib/passport-wsfed-saml2/samlp.js, package.json
Adding support for these two SAML request template variables so tenants can control these assertions on a per-connection basis.
- Destination
- AssertionConsumerServiceURL
https://auth0team.atlassian.net/browse/ULP-2795
> Describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If this library has unit and/or integration testing, tests should be added for new functionality and existing tests should complete without errors.
>
> Please include any manual steps for testing end-to-end or functionality not covered by unit/integration tests.
>
> Also include details of the environment this PR was developed in (language/platform/browser version).
=> add Destination & AssertionConsumerServiceURL as SAML req template vars

.github/workflows/ci.yml, .gitignore, .npmignore, .vscode/launch.json, package.json, test/saml11.tests.js, test/saml20.tests.js, test/samlp.tests.js, test/state/samlp.state.custom.tests.js, test/state/samlp.state.session.tests.js, test/state/wsfed.state.custom.tests.js, test/state/wsfed.state.session.tests.js
- Drop Node 10 ([No longer maintained](https://nodejs.org/en/about/releases/))
- Add back the missing `--recursive` flag so all tests run
- Add `npm run test-debug` command & VSCode launch config
- Remove `should` (Assertions were being done using 3 different libs, now down to 2)
- Remove `xml2js` (Not used)
- Bump several dev deps
- mocha
- chai
- istanbul -> nyc
- passport
- cheerio
- Some var -> const cleanup
=> Drop node 10, update/consolidate dev dependencies

lib/passport-wsfed-saml2/saml.js, package.json, test/samlp.tests.js, test/samples/plain/samlresponse_cr.xml
This change fixes the calculation of the digest when elements include XML character entities (`&#13;`, `&#xD`), e.g.:
```xml
<AttributeValue>Street 1&#13;
Line 2&#13;
Some more address.&#13;
City, state and zip goes here.
</AttributeValue>
```
Processors are supposed to normalize line endings (`CR`, `CRLF`, `LF`) to `LF` before parsing the XML, but the encoded entities should be converted only after this line ending normalization (so that, in the example above, the carriage return would remain in place).
The code, however, was doing an unnecessary XML doc -> string -> Xml doc conversion when validating a signature in the assertion, which caused these CR characters to be lost. In a simplified way, it was something like this:
```
// first processing of the original XML string
// line …
```
=> Handle encoded CR entities in assertions

lib/passport-wsfed-saml2/samlp.js, package.json
Allow AssertionConsumerServiceURL to be provided by `options.callback` OR `options.assertionConsumerServiceURL`.
> Describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If this library has unit and/or integration testing, tests should be added for new functionality and existing tests should complete without errors.
>
> Please include any manual steps for testing end-to-end or functionality not covered by unit/integration tests.
>
> Also include details of the environment this PR was developed in (language/platform/browser version).
=> Allow options.assertionConsumerServiceURL or options.callback

package.json
This change drops node 8 (no major bump since the library supports node
10+ anyway), and uses the native node crypto function
instead of node-forge
Version is not bumped yet due to a direct dependency with node-forge. We should also look into using the native crypto library. 
By submitting a PR to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md). Please see the [contributing guidelines](https://github.com/auth0/.github/blob/master/CONTRIBUTING.md) for how to create and submit a high-quality PR for this repo.
Addresses node-forge vulnerability: #141
#141
No additional tests other than pre-existing ones.
=> bump xml-encryption to 2.0.0

lib/passport-wsfed-saml2/samlp.js, package.json, test/samlp.tests.js
**Purpose**:  This PR solves an existing bug in SAML request URL construction during sign in. If the URL contains any fragments, the fragments are not always appended at the end of the URL after all the query params. 
Eg: When parsing https://example.com/#Test. 
- Actual: https://example.com/#Test?SAMLRequest=...&RelayState=...
- Expected:  https://example.com/?SAMLRequest=...&RelayState=...#Test
The PR solves the problem by stripping fragments and query from URL and then appending them in the correct order after parsing stage.
ESD Ticket: https://auth0team.atlassian.net/browse/ESD-19892 for more context
Added Unit tests for this fix covering typical URL examples with/without fragments & with/without query params
=> [ULP-3649][ULP-3712] Fix: URL fragments in SAML Sign in URLs

lib/passport-wsfed-saml2/wsfederation.js, test/wsfed.tests.js
By submitting a PR to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md). Please see the [contributing guidelines](https://github.com/auth0/.github/blob/master/CONTRIBUTING.md) for how to create and submit a high-quality PR for this repo.
This PR is to validate if we have more than one Assertion inside a token response for WS-Fed. This validation will ensure we're compliant with WS-Trust specs. 
https://auth0team.atlassian.net/browse/FDR-457
> Describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If this library has unit and/or integration testing, tests should be added for new functionality and existing tests should complete without errors. …
=> FDR-457 - Do not allow tokens to have more than one assertion for WS-Fed
